## Importar Librerias

In [28]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split

## Cargar datos

In [19]:
data_sindicados_unida = pd.read_excel('Data\\mp-sindicados-2024-2023.xlsx')

data_agraviados_unida = pd.read_excel('Data\\mp-agraviados-2024-2023.xlsx')

data_sindicados_unida = data_sindicados_unida[data_sindicados_unida["sexo_sindicados"].isin([12])]

In [21]:
data_sindicados_unida.head()

,num_corre,año_denuncia,reg_mes,dia_denuncia,dia_sem_denuncia,año_hecho,mes_hecho,dia_hecho,dia_sem_hecho,depto_ocu_hecho,mupio_ocu_hecho,zona_ocu_hecho,sexo_sindicados,edad_sind,g_edad_60ymas,g_edad_80ymas,g_edad_de0_80ymas,est_conyugal,delito_com,principales_delitos
0,1,2024,2,27,2,2024,1,29,1,19,1901,99,1,999,12,16,18,9,390,15
4,5,2024,3,21,4,2024,3,14,4,1,101,1,2,999,12,16,18,9,11,15
5,6,2024,3,21,4,2024,3,14,4,1,101,1,2,999,12,16,18,9,276,15
6,7,2024,2,6,2,2023,12,20,3,1,101,99,2,999,12,16,18,9,11,15
7,8,2024,2,6,2,2023,12,20,3,1,101,99,2,999,12,16,18,9,276,15

In [22]:
data_agraviados_unida.head()

,num_corre,año_denuncia,reg_mes,dia_denuncia,dia_sem_denuncia,año_hecho,mes_hecho,dia_hecho,dia_sem_hecho,depto_ocu_hecho,mupio_ocu_hecho,zona_ocu_hecho,edad_agrav,sexo_agraviados,g_edad_60ymas,g_edad_80ymas,g_edad_de0_80ymas,delito_com,principales_delitos
0,1,2024,2,27,2,2024,2,27,1,19,1901,99,999,2,12,16,18,390,15
1,2,2024,2,8,4,2021,2,8,5,3,312,99,999,9,12,16,18,107,15
2,3,2024,2,28,3,2020,2,28,3,1,101,99,999,9,12,16,18,107,15
3,4,2024,3,13,3,2023,3,13,2,2,208,99,999,1,12,16,18,107,15
4,5,2024,3,22,5,2024,3,22,4,1,108,99,999,1,12,16,18,107,15

### Limpieza de datos en sexo_sindicados

In [75]:
data_sindicados_unida = data_sindicados_unida[data_sindicados_unida["sexo_sindicados"].isin([1,2])]

## Primera Red Neural

In [ ]:
# Variables predictoras y objetivo
X = data_sindicados_unida[["g_edad_60ymas", "est_conyugal", "sexo_sindicados"]]
y = data_sindicados_unida["mes_hecho"]

In [64]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [65]:

model = Sequential()
model.add(Dense(16, input_dim=3, activation='relu')) #3 Columnas
model.add(Dense(16, activation='relu'))
num_classes = y.nunique()
print(num_classes)
model.add(Dense(num_classes, activation='softmax'))

13

C:\Users\james\.pyenv\pyenv-win\versions\3.13.5\Lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [66]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [67]:
model.fit(X_train, y_train, epochs=50, batch_size=64, validation_data=(X_test, y_test))

Epoch 1/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1177 - loss: 2.4474 - val_accuracy: 0.1120 - val_loss: 2.4266
Epoch 2/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1211 - loss: 2.4249 - val_accuracy: 0.1209 - val_loss: 2.4250
Epoch 3/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1223 - loss: 2.4232 - val_accuracy: 0.1147 - val_loss: 2.4223
Epoch 4/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1233 - loss: 2.4220 - val_accuracy: 0.1224 - val_loss: 2.4217
Epoch 5/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1232 - loss: 2.4211 - val_accuracy: 0.1226 - val_loss: 2.4207
Epoch 6/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1237 - loss: 2.4206 - val_accuracy: 0.1230 - val_loss: 2.4201
Epoch 7/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1244 - loss: 2.4203 - val_accuracy: 0.1238 - val_loss: 2.4197
Epoch 8/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1240 - loss: 2.4201 - val_accuracy: 0.1234 - val_loss: 2.4195
Epoch 9/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1240 - loss: 2.4200 - val_accuracy: 0.1238 - val_loss: 2.4194
Epoch 10/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1244 - loss: 2.4197 - val_accuracy: 0.1229 - val_loss: 2.4211
Epoch 11/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1243 - loss: 2.4196 - val_accuracy: 0.1239 - val_loss: 2.4238
Epoch 12/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1243 - loss: 2.4200 - val_accuracy: 0.1242 - val_loss: 2.4195
Epoch 13/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1244 - loss: 2.4194 - val_accuracy: 0.1239 - val_loss: 2.4197
Epoch 14/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1248 - loss: 2.4194 - val_accuracy: 0.1239 - val_loss: 2.4195
Epoch 15/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1245 - loss: 2.4193 - val_accuracy: 0.1226 - val_loss: 2.4192
Epoch 16/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1247 - loss: 2.4191 - val_accuracy: 0.1234 - val_loss: 2.4194
Epoch 17/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1247 - loss: 2.4191 - val_accuracy: 0.1231 - val_loss: 2.4195
Epoch 18/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1250 - loss: 2.4194 - val_accuracy: 0.1224 - val_loss: 2.4192
Epoch 19/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1254 - loss: 2.4190 - val_accuracy: 0.1242 - val_loss: 2.4196
Epoch 20/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1246 - loss: 2.4190 - val_accuracy: 0.1237 - val_loss: 2.4189
Epoch 21/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1251 - loss: 2.4191 - val_accuracy: 0.1241 - val_loss: 2.4190
Epoch 22/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1245 - loss: 2.4190 - val_accuracy: 0.1239 - val_loss: 2.4188
Epoch 23/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1243 - loss: 2.4195 - val_accuracy: 0.1226 - val_loss: 2.4221
Epoch 24/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1248 - loss: 2.4191 - val_accuracy: 0.1234 - val_loss: 2.4194
Epoch 25/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1248 - loss: 2.4189 - val_accuracy: 0.1236 - val_loss: 2.4188
Epoch 26/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1248 - loss: 2.4189 - val_accuracy: 0.1234 - val_loss: 2.4189
Epoch 27/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1254 - loss: 2.4189 - val_accuracy: 0.1233 - val_loss: 2.4194
Epoch 28/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1247 - loss: 2.4195 - val_accuracy: 0.1235 - val_loss: 2.4192
Epoch 29/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1246 - loss: 2.4190 - val_accuracy: 0.1235 - val_loss: 2.4194
Epoch 30/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1243 - loss: 2.4193 - val_accuracy: 0.1240 - val_loss: 2.4187
Epoch 31/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1251 - loss: 2.4189 - val_accuracy: 0.1235 - val_loss: 2.4186
Epoch 32/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.1250 - loss: 2.4188 - val_accuracy: 0.1234 - val_loss: 2.4190
Epoch 33/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.1250 - loss: 2.4188 - val_accuracy: 0.1225 - val_loss: 2.4189
Epoch 34/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.1247 - loss: 2.4188 - val_accuracy: 0.1236 - val_loss: 2.4188
Epoch 35/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 10s 1ms/step - accuracy: 0.1253 - loss: 2.4188 - val_accuracy: 0.1233 - val_loss: 2.4193
Epoch 36/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.1251 - loss: 2.4188 - val_accuracy: 0.1230 - val_loss: 2.4187
Epoch 37/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.1249 - loss: 2.4188 - val_accuracy: 0.1232 - val_loss: 2.4185
Epoch 38/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.1245 - loss: 2.4191 - val_accuracy: 0.1238 - val_loss: 2.4188
Epoch 39/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.1247 - loss: 2.4194 - val_accuracy: 0.1234 - val_loss: 2.4187
Epoch 40/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.1246 - loss: 2.4188 - val_accuracy: 0.1236 - val_loss: 2.4189
Epoch 41/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.1247 - loss: 2.4191 - val_accuracy: 0.1236 - val_loss: 2.4187
Epoch 42/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1251 - loss: 2.4186 - val_accuracy: 0.1235 - val_loss: 2.4187
Epoch 43/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1252 - loss: 2.4194 - val_accuracy: 0.1231 - val_loss: 2.4189
Epoch 44/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1250 - loss: 2.4187 - val_accuracy: 0.1226 - val_loss: 2.4190
Epoch 45/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1247 - loss: 2.4187 - val_accuracy: 0.1234 - val_loss: 2.4192
Epoch 46/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1253 - loss: 2.4187 - val_accuracy: 0.1226 - val_loss: 2.4187
Epoch 47/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1248 - loss: 2.4187 - val_accuracy: 0.1234 - val_loss: 2.4185
Epoch 48/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1249 - loss: 2.4188 - val_accuracy: 0.1238 - val_loss: 2.4188
Epoch 49/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1247 - loss: 2.4187 - val_accuracy: 0.1238 - val_loss: 2.4186
Epoch 50/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1250 - loss: 2.4187 - val_accuracy: 0.1236 - val_loss: 2.4191

In [68]:
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Loss: {loss}, Accuracy: {accuracy}')

3210/3210 ━━━━━━━━━━━━━━━━━━━━ 3s 854us/step - accuracy: 0.1236 - loss: 2.4191
Loss: 2.4190855026245117, Accuracy: 0.12355776131153107

In [74]:
hecho = np.array([[
    9,
    1,
    1]])
res = model.predict(hecho)

print(res)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
[[3.0993725e-08 6.4844564e-02 5.8813151e-02 6.4396508e-02 8.7158263e-02
  9.5804490e-02 9.3157671e-02 9.2189632e-02 9.2929065e-02 9.0533651e-02
  8.8521115e-02 8.4878325e-02 8.6773604e-02]]

## Segunda Red neuronal

### Red dia_sem_hecho

In [102]:
# Variables predictoras y objetivo
X = data_sindicados_unida[["año_denuncia", "dia_denuncia", "mes_hecho","depto_ocu_hecho"]]
y = data_sindicados_unida["dia_sem_hecho"]

In [103]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [115]:
model = Sequential()
model.add(Dense(16, input_dim=4, activation='relu')) #3 Columnas
model.add(Dense(16, activation='relu'))



model.add(Dense(9, activation='softmax'))

C:\Users\james\.pyenv\pyenv-win\versions\3.13.5\Lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [116]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [117]:
model.fit(X_train, y_train, epochs=50, batch_size=64, validation_data=(X_test, y_test))

Epoch 1/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1617 - loss: 5.4800 - val_accuracy: 0.1651 - val_loss: 2.0504
Epoch 2/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1649 - loss: 2.0199 - val_accuracy: 0.1623 - val_loss: 2.0562
Epoch 3/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 16s 2ms/step - accuracy: 0.1660 - loss: 2.0059 - val_accuracy: 0.1848 - val_loss: 2.0119
Epoch 4/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1671 - loss: 1.9944 - val_accuracy: 0.1623 - val_loss: 2.1681
Epoch 5/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1683 - loss: 1.9782 - val_accuracy: 0.1657 - val_loss: 1.9225
Epoch 6/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1696 - loss: 1.9630 - val_accuracy: 0.1572 - val_loss: 1.9626
Epoch 7/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1721 - loss: 1.9460 - val_accuracy: 0.1696 - val_loss: 1.9201
Epoch 8/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1768 - loss: 1.9267 - val_accuracy: 0.1854 - val_loss: 1.9228
Epoch 9/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1819 - loss: 1.9191 - val_accuracy: 0.1854 - val_loss: 1.9169
Epoch 10/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1851 - loss: 1.9181 - val_accuracy: 0.1854 - val_loss: 1.9167
Epoch 11/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1860 - loss: 1.9172 - val_accuracy: 0.1854 - val_loss: 1.9160
Epoch 12/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1862 - loss: 1.9169 - val_accuracy: 0.1854 - val_loss: 1.9155
Epoch 13/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1862 - loss: 1.9165 - val_accuracy: 0.1854 - val_loss: 1.9157
Epoch 14/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1863 - loss: 1.9162 - val_accuracy: 0.1854 - val_loss: 1.9151
Epoch 15/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1863 - loss: 1.9160 - val_accuracy: 0.1854 - val_loss: 1.9149
Epoch 16/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1863 - loss: 1.9158 - val_accuracy: 0.1854 - val_loss: 1.9161
Epoch 17/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1863 - loss: 1.9156 - val_accuracy: 0.1854 - val_loss: 1.9144
Epoch 18/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1863 - loss: 1.9151 - val_accuracy: 0.1854 - val_loss: 1.9140
Epoch 19/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1863 - loss: 1.9171 - val_accuracy: 0.1854 - val_loss: 1.9171
Epoch 20/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1863 - loss: 1.9173 - val_accuracy: 0.1854 - val_loss: 1.9170
Epoch 21/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1863 - loss: 1.9174 - val_accuracy: 0.1854 - val_loss: 1.9170
Epoch 22/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1863 - loss: 1.9174 - val_accuracy: 0.1854 - val_loss: 1.9171
Epoch 23/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1863 - loss: 1.9174 - val_accuracy: 0.1854 - val_loss: 1.9171
Epoch 24/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1863 - loss: 1.9174 - val_accuracy: 0.1854 - val_loss: 1.9170
Epoch 25/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1863 - loss: 1.9174 - val_accuracy: 0.1854 - val_loss: 1.9171
Epoch 26/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1863 - loss: 1.9174 - val_accuracy: 0.1854 - val_loss: 1.9171
Epoch 27/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1863 - loss: 1.9174 - val_accuracy: 0.1854 - val_loss: 1.9171
Epoch 28/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1863 - loss: 1.9174 - val_accuracy: 0.1854 - val_loss: 1.9170
Epoch 29/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1863 - loss: 1.9173 - val_accuracy: 0.1854 - val_loss: 1.9170
Epoch 30/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1863 - loss: 1.9174 - val_accuracy: 0.1854 - val_loss: 1.9171
Epoch 31/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1863 - loss: 1.9174 - val_accuracy: 0.1854 - val_loss: 1.9170
Epoch 32/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1863 - loss: 1.9174 - val_accuracy: 0.1854 - val_loss: 1.9170
Epoch 33/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1863 - loss: 1.9174 - val_accuracy: 0.1854 - val_loss: 1.9170
Epoch 34/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1863 - loss: 1.9174 - val_accuracy: 0.1854 - val_loss: 1.9171
Epoch 35/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1863 - loss: 1.9174 - val_accuracy: 0.1854 - val_loss: 1.9171
Epoch 36/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1863 - loss: 1.9173 - val_accuracy: 0.1854 - val_loss: 1.9171
Epoch 37/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1863 - loss: 1.9174 - val_accuracy: 0.1854 - val_loss: 1.9170
Epoch 38/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1863 - loss: 1.9174 - val_accuracy: 0.1854 - val_loss: 1.9172
Epoch 39/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1863 - loss: 1.9174 - val_accuracy: 0.1854 - val_loss: 1.9170
Epoch 40/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1863 - loss: 1.9174 - val_accuracy: 0.1854 - val_loss: 1.9171
Epoch 41/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.1863 - loss: 1.9174 - val_accuracy: 0.1854 - val_loss: 1.9170
Epoch 42/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - accuracy: 0.1863 - loss: 1.9174 - val_accuracy: 0.1854 - val_loss: 1.9170
Epoch 43/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.1863 - loss: 1.9174 - val_accuracy: 0.1854 - val_loss: 1.9170
Epoch 44/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1863 - loss: 1.9174 - val_accuracy: 0.1854 - val_loss: 1.9171
Epoch 45/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1863 - loss: 1.9174 - val_accuracy: 0.1854 - val_loss: 1.9171
Epoch 46/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.1863 - loss: 1.9174 - val_accuracy: 0.1854 - val_loss: 1.9170
Epoch 47/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1863 - loss: 1.9174 - val_accuracy: 0.1854 - val_loss: 1.9170
Epoch 48/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1863 - loss: 1.9174 - val_accuracy: 0.1854 - val_loss: 1.9170
Epoch 49/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1863 - loss: 1.9174 - val_accuracy: 0.1854 - val_loss: 1.9171
Epoch 50/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.1863 - loss: 1.9174 - val_accuracy: 0.1854 - val_loss: 1.9170

In [118]:
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Loss: {loss}, Accuracy: {accuracy}')

3210/3210 ━━━━━━━━━━━━━━━━━━━━ 3s 884us/step - accuracy: 0.1854 - loss: 1.9170
Loss: 1.9170070886611938, Accuracy: 0.18544374406337738

In [120]:
hecho = np.array([[
    2024,
    8,
    5,
    1]])
res = model.predict(hecho)
print(res)

hecho = np.array([[
    2023,
    8,
    5,
    9]])
res = model.predict(hecho)
print(res)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[[1.16987005e-01 1.85676351e-01 1.66931123e-01 1.63488790e-01
  1.58529848e-01 1.27981246e-01 8.03589821e-02 4.66593083e-05
  5.15666509e-10]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
[[1.16987005e-01 1.85676351e-01 1.66931123e-01 1.63488790e-01
  1.58529848e-01 1.27981246e-01 8.03589821e-02 4.66593083e-05
  5.15666509e-10]]

## Tercera Red neuronal

In [124]:
# Variables predictoras y objetivo
X = data_sindicados_unida[["sexo_sindicados", "depto_ocu_hecho", "est_conyugal"]]
y = data_sindicados_unida["g_edad_de0_80ymas"]

In [125]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [136]:
model = Sequential()
model.add(Dense(16, input_dim=3, activation='relu'))  #3 Columnas
model.add(Dense(16, activation='relu'))

num_classes = y.nunique()
print(num_classes)

model.add(Dense(19, activation='softmax'))

18

C:\Users\james\.pyenv\pyenv-win\versions\3.13.5\Lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [137]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [138]:
model.fit(X_train, y_train, epochs=50, batch_size=64, validation_data=(X_test, y_test))

Epoch 1/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 10s 1ms/step - accuracy: 0.4097 - loss: 2.0098 - val_accuracy: 0.4160 - val_loss: 1.9693
Epoch 2/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 13s 2ms/step - accuracy: 0.4149 - loss: 1.9686 - val_accuracy: 0.4146 - val_loss: 1.9671
Epoch 3/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - accuracy: 0.4157 - loss: 1.9625 - val_accuracy: 0.4171 - val_loss: 1.9599
Epoch 4/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - accuracy: 0.4166 - loss: 1.9593 - val_accuracy: 0.4187 - val_loss: 1.9584
Epoch 5/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.4170 - loss: 1.9582 - val_accuracy: 0.4160 - val_loss: 1.9571
Epoch 6/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.4168 - loss: 1.9576 - val_accuracy: 0.4176 - val_loss: 1.9567
Epoch 7/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 10s 1ms/step - accuracy: 0.4167 - loss: 1.9574 - val_accuracy: 0.4187 - val_loss: 1.9560
Epoch 8/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.4169 - loss: 1.9569 - val_accuracy: 0.4180 - val_loss: 1.9561
Epoch 9/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.4167 - loss: 1.9566 - val_accuracy: 0.4182 - val_loss: 1.9590
Epoch 10/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 10s 1ms/step - accuracy: 0.4169 - loss: 1.9565 - val_accuracy: 0.4172 - val_loss: 1.9579
Epoch 11/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.4170 - loss: 1.9565 - val_accuracy: 0.4182 - val_loss: 1.9562
Epoch 12/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - accuracy: 0.4166 - loss: 1.9562 - val_accuracy: 0.4186 - val_loss: 1.9550
Epoch 13/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 10s 1ms/step - accuracy: 0.4168 - loss: 1.9561 - val_accuracy: 0.4183 - val_loss: 1.9556
Epoch 14/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 10s 1ms/step - accuracy: 0.4169 - loss: 1.9559 - val_accuracy: 0.4180 - val_loss: 1.9570
Epoch 15/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - accuracy: 0.4170 - loss: 1.9558 - val_accuracy: 0.4179 - val_loss: 1.9566
Epoch 16/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.4170 - loss: 1.9558 - val_accuracy: 0.4188 - val_loss: 1.9561
Epoch 17/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.4172 - loss: 1.9555 - val_accuracy: 0.4178 - val_loss: 1.9561
Epoch 18/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.4170 - loss: 1.9555 - val_accuracy: 0.4181 - val_loss: 1.9547
Epoch 19/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - accuracy: 0.4168 - loss: 1.9555 - val_accuracy: 0.4181 - val_loss: 1.9541
Epoch 20/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - accuracy: 0.4170 - loss: 1.9553 - val_accuracy: 0.4173 - val_loss: 1.9550
Epoch 21/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - accuracy: 0.4173 - loss: 1.9551 - val_accuracy: 0.4181 - val_loss: 1.9552
Epoch 22/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - accuracy: 0.4172 - loss: 1.9551 - val_accuracy: 0.4181 - val_loss: 1.9542
Epoch 23/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 10s 1ms/step - accuracy: 0.4171 - loss: 1.9550 - val_accuracy: 0.4175 - val_loss: 1.9546
Epoch 24/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.4171 - loss: 1.9549 - val_accuracy: 0.4190 - val_loss: 1.9546
Epoch 25/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.4169 - loss: 1.9549 - val_accuracy: 0.4184 - val_loss: 1.9546
Epoch 26/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.4169 - loss: 1.9549 - val_accuracy: 0.4182 - val_loss: 1.9538
Epoch 27/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.4172 - loss: 1.9547 - val_accuracy: 0.4181 - val_loss: 1.9543
Epoch 28/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.4173 - loss: 1.9545 - val_accuracy: 0.4178 - val_loss: 1.9554
Epoch 29/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.4173 - loss: 1.9546 - val_accuracy: 0.4179 - val_loss: 1.9540
Epoch 30/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.4169 - loss: 1.9545 - val_accuracy: 0.4176 - val_loss: 1.9549
Epoch 31/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.4171 - loss: 1.9544 - val_accuracy: 0.4182 - val_loss: 1.9549
Epoch 32/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.4168 - loss: 1.9545 - val_accuracy: 0.4173 - val_loss: 1.9555
Epoch 33/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.4171 - loss: 1.9543 - val_accuracy: 0.4183 - val_loss: 1.9546
Epoch 34/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - accuracy: 0.4171 - loss: 1.9543 - val_accuracy: 0.4181 - val_loss: 1.9561
Epoch 35/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 10s 1ms/step - accuracy: 0.4170 - loss: 1.9543 - val_accuracy: 0.4180 - val_loss: 1.9532
Epoch 36/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 10s 1ms/step - accuracy: 0.4170 - loss: 1.9541 - val_accuracy: 0.4176 - val_loss: 1.9536
Epoch 37/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - accuracy: 0.4170 - loss: 1.9542 - val_accuracy: 0.4174 - val_loss: 1.9554
Epoch 38/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - accuracy: 0.4173 - loss: 1.9542 - val_accuracy: 0.4180 - val_loss: 1.9546
Epoch 39/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - accuracy: 0.4172 - loss: 1.9542 - val_accuracy: 0.4181 - val_loss: 1.9552
Epoch 40/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - accuracy: 0.4173 - loss: 1.9541 - val_accuracy: 0.4190 - val_loss: 1.9533
Epoch 41/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 10s 1ms/step - accuracy: 0.4170 - loss: 1.9541 - val_accuracy: 0.4173 - val_loss: 1.9562
Epoch 42/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - accuracy: 0.4171 - loss: 1.9540 - val_accuracy: 0.4180 - val_loss: 1.9546
Epoch 43/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.4172 - loss: 1.9541 - val_accuracy: 0.4185 - val_loss: 1.9538
Epoch 44/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.4171 - loss: 1.9540 - val_accuracy: 0.4182 - val_loss: 1.9533
Epoch 45/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.4170 - loss: 1.9539 - val_accuracy: 0.4181 - val_loss: 1.9552
Epoch 46/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.4175 - loss: 1.9539 - val_accuracy: 0.4177 - val_loss: 1.9542
Epoch 47/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.4173 - loss: 1.9539 - val_accuracy: 0.4183 - val_loss: 1.9537
Epoch 48/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.4173 - loss: 1.9539 - val_accuracy: 0.4190 - val_loss: 1.9532
Epoch 49/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.4173 - loss: 1.9539 - val_accuracy: 0.4183 - val_loss: 1.9533
Epoch 50/50
6420/6420 ━━━━━━━━━━━━━━━━━━━━ 10s 1ms/step - accuracy: 0.4172 - loss: 1.9539 - val_accuracy: 0.4183 - val_loss: 1.9533

In [141]:
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Loss: {loss}, Accuracy: {accuracy}')

3210/3210 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - accuracy: 0.4183 - loss: 1.9533
Loss: 1.9532644748687744, Accuracy: 0.4183048605918884

In [140]:
hecho = np.array([[
    1,
    1,
    2]])
res = model.predict(hecho)

print(res)
hecho = np.array([[
    2,
    1,
    2]])
res = model.predict(hecho)

print(res)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
[[5.7646721e-10 2.0368455e-04 1.4791049e-13 1.8105644e-04 6.3565499e-03
  2.9493382e-02 8.5505567e-02 1.5819129e-01 1.6397862e-01 1.4546899e-01
  1.0387793e-01 8.1298888e-02 4.9050454e-02 3.4335434e-02 2.4455942e-02
  1.3421434e-02 4.6750451e-03 2.8603899e-03 9.6645296e-02]]